theme: jekyll-theme-slate 
title: This is the YY's personal homepage,
description: From media, communication and tourism studies in Hokkaido University
plugins: 
    - jemoji 
url: "http://YY2333333.github.io/" 
markdown: kramdown
