theme: jekyll-theme-slate 
title: YY's
describe: This is the YY's personal homepage, from media, communication and tourism studies in Hokkaido University
plugins: 
    - jemoji 
url: "YY2333333.github.io" 
markdown: kramdown
